version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-mydatabase}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      DATABASE_URL: postgres://${DATABASE_USER:-user}:${DATABASE_PASSWORD:-password}@db:${DATABASE_PORT:-5432}/${DATABASE_NAME:-mydatabase}
    depends_on:
      - db

volumes:
  db_data: 